wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/train.py
    framework: huggingface
    huggingface_version: 4.16.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-AdamW
      5: 1
      6:
      - 1
    - 1: Training/Accuracy
      5: 1
      6:
      - 1
    - 1: Training/Loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: Validation/Accuracy
      5: 1
      6:
      - 1
    - 1: Validation/Loss
      5: 1
      6:
      - 1
    python_version: 3.9.6
    start_time: 1645613569
    t:
      1:
      - 1
      - 9
      - 11
      2:
      - 1
      - 9
      - 11
      3:
      - 7
      - 16
      4: 3.9.6
      5: 0.12.10
      6: 4.16.0
      8:
      - 5
batch_first:
  desc: null
  value: true
batch_size:
  desc: null
  value: 512
betas:
  desc: null
  value:
  - 0.9
  - 0.98
context_len:
  desc: null
  value: 5
dropout:
  desc: null
  value: 0
heads:
  desc: null
  value: 4
layers:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.0003
max_seq_len:
  desc: null
  value: 5
num_samples:
  desc: null
  value: 10000
num_tokens:
  desc: null
  value: 26
optim_kwargs:
  desc: null
  value:
    betas:
    - 0.9
    - 0.98
    lr: 0.0003
    weight_decay: 1
optim_kwargs/betas:
  desc: null
  value:
  - 0.9
  - 0.98
optim_kwargs/lr:
  desc: null
  value: 0.0003
optim_kwargs/weight_decay:
  desc: null
  value: 1
seed:
  desc: null
  value: 42
steps:
  desc: null
  value: 100000
weight_decay:
  desc: null
  value: 1
width:
  desc: null
  value: 128
